name: Build and Push Docker Image

on:
  pull_request:
    types: [closed]
    branches:
      - main
      
jobs:
  build-and-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set up tag for the Docker image
      id: vars
      run: echo "TAG=$(date +%s)" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build . --file car_pred/Dockerfile --tag chidubem/car-pred_app:${{ env.TAG }}

    - name: Push the Docker image
      run: docker push chidubem/car-pred_app:${{ env.TAG }}

    - name: Log out from Docker Hub
      run: docker logout
